# fly.toml app configuration file generated for cryo-mcp on 2025-06-02T15:14:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cryo-mcp'
primary_region = 'fra'
swap_size_mb = 8192

[build]

[env]
DEBUG = 'cryo:*,payflow-sdk'
NODE_ENV = 'production'

[[mounts]]
source = 'cryo_mcp_data'
destination = '/app/examples/cryo-mcp/data'

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 4
